import { useRef, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Sparkles, ArrowUp, Info } from 'lucide-react';
import type { Transaction } from '../../transactions/types';
import { getAskProvider, type AskAnswer } from '../ask';

/**
 * "Ask Expense Machine" — a conversational interface over the rule-based
 * intelligence engine. It is explicitly built-in analysis, not an LLM: each
 * answer is computed from the real ledger and labelled with its source. The
 * provider abstraction (ask.ts) leaves a clean seam for a future Claude/OpenAI
 * backend, but nothing here claims to be AI.
 */

interface Turn {
  role: 'user' | 'machine';
  text: string;
  answer?: AskAnswer;
}

const SUGGESTIONS = [
  'Predict my savings by year end',
  'Why did my spending increase?',
  'What category should I reduce first?',
  'Am I on track with my budgets?',
];

export function AskPanel({ txns }: { txns: Transaction[] }) {
  const [turns, setTurns] = useState<Turn[]>([]);
  const [input, setInput] = useState('');
  const [busy, setBusy] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  const submit = async (question: string) => {
    const q = question.trim();
    if (!q || busy) return;
    setInput('');
    setTurns((t) => [...t, { role: 'user', text: q }]);
    setBusy(true);
    try {
      const provider = getAskProvider();
      const answer = await provider.ask(q, txns);
      setTurns((t) => [...t, { role: 'machine', text: answer.text, answer }]);
    } catch (err: unknown) {
      console.error('[AskPanel] Analysis failed:', err);
      setTurns((t) => [...t, { role: 'machine', text: 'Something went wrong analysing that. Please try rephrasing.' }]);
    } finally {
      setBusy(false);
      requestAnimationFrame(() => {
        scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' });
      });
    }
  };

  return (
    <div className="overflow-hidden rounded-panel border border-hairline bg-surface">
      {/* header */}
      <div className="flex items-center gap-2.5 border-b border-hairline px-5 py-3.5">
        <Sparkles size={15} className="text-brass" strokeWidth={1.75} />
        <h3 className="font-serif text-[1.05rem] text-bright">Ask Expense Machine</h3>
        <span className="ml-auto flex items-center gap-1 font-mono text-[0.56rem] uppercase tracking-wider text-faint">
          <Info size={10} /> Built-in analysis
        </span>
      </div>

      {/* conversation */}
      <div ref={scrollRef} className="max-h-72 overflow-y-auto px-5 py-4">
        {turns.length === 0 ? (
          <div className="py-2">
            <p className="mb-3 text-[0.85rem] text-muted">
              Ask about your spending, savings forecast, budgets, or merchants.
              Answers are computed from your real data — not generated by an AI.
            </p>
            <div className="flex flex-wrap gap-2">
              {SUGGESTIONS.map((s) => (
                <button
                  key={s}
                  type="button"
                  onClick={() => submit(s)}
                  className="rounded-full border border-hairline px-3 py-1.5 text-[0.76rem] text-soft transition-colors hover:border-brass-deep hover:text-bright"
                >
                  {s}
                </button>
              ))}
            </div>
          </div>
        ) : (
          <div className="flex flex-col gap-3">
            <AnimatePresence initial={false}>
              {turns.map((turn, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 6 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.25, ease: [0.22, 1, 0.36, 1] }}
                  className={turn.role === 'user' ? 'flex justify-end' : 'flex justify-start'}
                >
                  <div
                    className={[
                      'max-w-[85%] whitespace-pre-line rounded-panel px-3.5 py-2.5 text-[0.85rem] leading-relaxed',
                      turn.role === 'user'
                        ? 'bg-brass-deep/25 text-bright'
                        : 'border border-hairline bg-elevated text-soft',
                    ].join(' ')}
                  >
                    {turn.text}
                  </div>
                </motion.div>
              ))}
            </AnimatePresence>
            {busy && (
              <div className="flex justify-start">
                <div className="rounded-panel border border-hairline bg-elevated px-3.5 py-2.5 text-[0.8rem] text-faint">
                  Analysing…
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      {/* input */}
      <div className="border-t border-hairline p-3">
        <div className="flex items-center gap-2 rounded-control border border-hairline bg-ground px-3 py-1.5 focus-within:border-brass">
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter') submit(input);
            }}
            placeholder="Ask about your finances…"
            className="flex-1 bg-transparent text-[0.86rem] text-bright placeholder:text-faint focus:outline-none"
          />
          <button
            type="button"
            onClick={() => submit(input)}
            disabled={!input.trim() || busy}
            aria-label="Ask"
            className="flex h-7 w-7 items-center justify-center rounded-control bg-brass text-void transition-colors hover:bg-brass-bright disabled:opacity-40"
          >
            <ArrowUp size={15} strokeWidth={2.2} />
          </button>
        </div>
      </div>
    </div>
  );
}
