import { useState } from 'react';
import { useNavigate, useSearchParams, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, Lock } from 'lucide-react';
import { BrandMark } from '../../components/primitives/BrandMark';
import { authStore, AuthError } from './store';
import { EASE } from '../motion/primitives';

/**
 * Step 4–6 of the password-reset flow: the user lands here from the link
 * generated by `authStore.requestPasswordReset`. We validate the one-time
 * token up front (rejecting missing/expired/used tokens) before letting the
 * user choose a new password. `authStore.resetPassword` enforces the same
 * checks again and marks the token used, so it cannot be replayed.
 */
export function ResetPasswordPage() {
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const token = params.get('token') ?? '';
  const valid = authStore.validateResetToken(token);

  const [password, setPassword] = useState('');
  const [confirm, setConfirm] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [done, setDone] = useState(false);

  const submit = () => {
    setError(null);
    if (password !== confirm) {
      setError('Passwords do not match.');
      return;
    }
    try {
      authStore.resetPassword(token, password);
      setDone(true);
    } catch (e) {
      setError(e instanceof AuthError ? e.message : 'Something went wrong. Please try again.');
    }
  };

  return (
    <div className="em-halo relative flex min-h-screen items-center justify-center overflow-hidden bg-ground px-5 py-12">
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, ease: EASE }}
        className="relative z-[1] w-full max-w-md"
      >
        <div className="mb-9 flex flex-col items-center text-center">
          <div className="mb-5 flex items-center justify-center">
            <BrandMark glyphOnly size={48} />
          </div>
          <p className="mb-2 font-mono text-[0.62rem] uppercase tracking-[0.24em] text-brass">
            Expense Machine
          </p>
          <h1 className="font-serif text-[2rem] leading-tight text-bright">
            {!valid ? 'Reset link invalid' : done ? 'Password updated' : 'Choose a new password'}
          </h1>
          <p className="mt-2 max-w-sm text-[0.9rem] text-muted">
            {!valid
              ? 'This link is invalid, expired, or has already been used. Request a new one from the login page.'
              : done
                ? 'Your password has been updated. Sign in with your new password.'
                : 'Pick a new password for your account.'}
          </p>
        </div>

        <div className="rounded-panel border border-hairline bg-surface p-7">
          {!valid || done ? (
            <button
              type="button"
              onClick={() => navigate('/login', { replace: true })}
              className="flex h-11 w-full items-center justify-center gap-2.5 rounded-control bg-brass text-[0.9rem] font-medium text-void transition-colors duration-300 ease-lux hover:bg-brass-bright"
            >
              Back to sign in
              <ArrowRight size={16} strokeWidth={2} />
            </button>
          ) : (
            <div className="flex flex-col gap-4">
              <label className="block">
                <span className="mb-1.5 block font-mono text-[0.6rem] uppercase tracking-[0.14em] text-faint">
                  New password
                </span>
                <span className="relative flex items-center">
                  <span className="pointer-events-none absolute left-3.5 text-faint"><Lock size={15} /></span>
                  <input
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="At least 6 characters"
                    autoComplete="new-password"
                    className="h-11 w-full rounded-control border border-hairline bg-ground pl-10 pr-3 text-[0.9rem] text-bright placeholder:text-faint transition-colors duration-300 ease-lux focus:border-brass focus:outline-none"
                  />
                </span>
              </label>
              <label className="block">
                <span className="mb-1.5 block font-mono text-[0.6rem] uppercase tracking-[0.14em] text-faint">
                  Confirm password
                </span>
                <span className="relative flex items-center">
                  <span className="pointer-events-none absolute left-3.5 text-faint"><Lock size={15} /></span>
                  <input
                    type="password"
                    value={confirm}
                    onChange={(e) => setConfirm(e.target.value)}
                    placeholder="Re-enter new password"
                    autoComplete="new-password"
                    className="h-11 w-full rounded-control border border-hairline bg-ground pl-10 pr-3 text-[0.9rem] text-bright placeholder:text-faint transition-colors duration-300 ease-lux focus:border-brass focus:outline-none"
                  />
                </span>
              </label>

              {error && (
                <div className="rounded-control border border-loss/40 bg-loss/10 px-3.5 py-2.5 text-[0.82rem] text-loss">
                  {error}
                </div>
              )}

              <button
                type="button"
                onClick={submit}
                className="mt-1 flex h-11 w-full items-center justify-center gap-2.5 rounded-control bg-brass text-[0.9rem] font-medium text-void transition-colors duration-300 ease-lux hover:bg-brass-bright"
              >
                Update password
                <ArrowRight size={16} strokeWidth={2} />
              </button>
            </div>
          )}
        </div>

        <p className="mt-6 text-center text-[0.85rem] text-muted">
          <Link to="/login" className="text-brass underline-offset-2 transition-colors hover:underline">
            Back to sign in
          </Link>
        </p>
      </motion.div>
    </div>
  );
}
